services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - data:/data/db
    ports:
      - '27017:27017'

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'

  judge-env:
    image: judge:1.0
    build:
      context: .
      dockerfile: Dockerfile.judge
    command: ["true"]

  backend:
    container_name: sandbox-judge
    build: .
    ports:
      - '5000:5000'
    volumes:
      - logs:/app/logs
      - ./src:/app/src
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock # allow backend to run docker
      - /tmp:/tmp # share temp files with runner
    environment:
      - MONGO_URI=mongodb://mongodb:27017/SandboxJudge
    depends_on:
      - mongodb
      - redis

volumes:
  data:
  logs:
